### ISSUE TITLE
[Common] 색상별(빨강/회) 버튼 컴포넌트 추가

### ISSUE THREAD

**Issue by BangGiSeung** [Minhee-Jeon/prodoo#12]
- class추가 방식 (빨간색/회색), width, message가 상태 될수있게

**Comment by Minhee-Jeon** [comment]
common 컴포넌트 Button을 만들면서 color를 입력받아 생성시 해당 color className을 추가하도록 구현했으므로 색상별 컴포넌트를 추가하는 해당 이슈는 닫습니다.
